name: weather_page_ui
description: "free flutter ui is all you need"
#publish_to: 'none'
repository: https://github.com/flutter-uihub/weather_page_ui

version: 1.0.2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  assets:
    - assets/uihub/weather_page_ui/
  uses-material-design: true

topics:
  - uihub